/*-
 * $Id$
 */
package com.github.unix_junkie.christmas;

/**
 * @author Andrew ``Bass'' Shcheglov (andrewbass@gmail.com)
 */
public enum LineDrawingCharacters {
	BOX_DRAWINGS_LIGHT_HORIZONTAL('\u2500'),
	BOX_DRAWINGS_LIGHT_VERTICAL('\u2502'),
	BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT('\u250c'),
	BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT('\u2510'),
	BOX_DRAWINGS_LIGHT_UP_AND_RIGHT('\u2514'),
	BOX_DRAWINGS_LIGHT_UP_AND_LEFT('\u2518'),
	BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT('\u251c'),
	BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT('\u2524'),
	BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL('\u252c'),
	BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL('\u2534'),
	BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL('\u253c'),
	BOX_DRAWINGS_DOUBLE_HORIZONTAL('\u2550'),
	BOX_DRAWINGS_DOUBLE_VERTICAL('\u2551'),
	BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE('\u2552'),
	BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE('\u2553'),
	BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT('\u2554'),
	BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE('\u2555'),
	BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE('\u2556'),
	BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT('\u2557'),
	BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE('\u2558'),
	BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE('\u2559'),
	BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT('\u255a'),
	BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE('\u255b'),
	BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE('\u255c'),
	BOX_DRAWINGS_DOUBLE_UP_AND_LEFT('\u255d'),
	BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE('\u255e'),
	BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE('\u255f'),
	BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT('\u2560'),
	BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE('\u2561'),
	BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE('\u2562'),
	BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT('\u2563'),
	BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE('\u2564'),
	BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE('\u2565'),
	BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL('\u2566'),
	BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE('\u2567'),
	BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE('\u2568'),
	BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL('\u2569'),
	BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE('\u256a'),
	BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE('\u256b'),
	BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL('\u256c'),
	UPPER_HALF_BLOCK('\u2580'),
	LOWER_HALF_BLOCK('\u2584'),
	FULL_BLOCK('\u2588'),
	LEFT_HALF_BLOCK('\u258c'),
	RIGHT_HALF_BLOCK('\u2590'),
	LIGHT_SHADE('\u2591'),
	MEDIUM_SHADE('\u2592'),
	DARK_SHADE('\u2593'),
	;

	private final char character;

	/**
	 * @param character
	 */
	private LineDrawingCharacters(final char character) {
		this.character = character;
	}

	public char getCharacter() {
		return this.character;
	}
}
